### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by priyanshi2001**
Added Navbar

### CODE REVIEW

**Comment by Ajay-Singhroha** [comment]
@priyanshi2001 I see you have added styles of navbar in both HTML and CSS file if style written in CSS file is working for the navbar, then no need in the index.html file.
I added some styles in inddex.html because they were not working when in style.css

**Comment by priyanshi2001** [comment]
Yeah I added in style.css first but they were not working in my browser then I added in the html file itself.But if they are working,no problem!

**Comment by Ajay-Singhroha** [comment]
Same happened with me also, let's see the problem

**Comment by dewanhimanshu** [comment]
@priyanshi2001  can you share a screen shot of what you have created?

**Comment by priyanshi2001** [comment]
Yeah Sure!
This is how it looks like.I have added 5 default options.
navbar

**Pull request merged**
